// **docset.types**
//
// Types used in a Docset.
//
// [Listing.](https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/HeaderDoc/anchors/anchors.html#//apple_ref/doc/uid/TP40001215-CH347-SW1)

var docset = {};

// Holds a mapping of type names to type symbols.

docset.types = {
  SNIPPET: 'Snippet',
  CLASS: [ 'Class', 'cl', 'tmplt', 'specialization' ],
  _STRUCT: '_Struct',
  TAG: 'Tag',
  TRAIT: 'Trait',
  DATABASE: 'Database',
  PROTOCOL: [ 'Protocol', 'intf' ],
  DELEGATE: 'Delegate',
  INTERFACE: 'Interface',
  INDIRECTION: 'Indirection',
  OBJECT: 'Object',
  SCHEMA: 'Schema',
  CATEGORY: [ 'Category', 'cat', 'Groups', 'Pages' ],
  FRAMEWORK: 'Framework',
  MODULE: 'Module',
  LIBRARY: 'Library',
  NAMESPACE: 'Namespace',
  PACKAGE: 'Package',
  EXCEPTION: 'Exception',
  ERROR: 'Error',
  DIAGRAM: 'Diagram',
  TABLE: 'Table',
  QUERY: 'Query',
  COMPONENT: 'Component',
  CONSTRUCTOR: [ 'Constructor', 'Public Constructor' ],
  ELEMENT: 'Element',
  RESOURCE: 'Resource',
  DIRECTIVE: 'Directive',
  EXTENSION: 'Extension',
  PLUGIN: 'Plugin',
  FILTER: 'Filter',
  SERVICE: 'Service',
  PROVIDER: 'Provider',
  METHOD: [ 'Method', 'instm', 'intfm', 'clm', 'intfcm', 'Class Methods', 'Instance Mehtods', 'Public Methods', 'Inherited Methods', 'Private Methods', 'Protected Methods', 'instctr', 'intfctr' ],
  INDEX: 'Index',
  MIXIN: 'Mixin',
  EVENT: [ 'Event', 'event', 'Public Events', 'Inherited Events', 'Private Events' ],
  BINDING: [ 'Binding', 'binding' ],
  ENTRY: 'Entry',
  FOREIGN_KEY: 'Foreign Key',
  GUIDE: [ 'Guide', 'doc' ],
  SAMPLE: 'Sample',
  RECORD: 'Record',
  REPORT: 'Report',
  MODIFIER: 'Modifier',
  SHORTCUT: 'Shortcut',
  HOOK: 'Hook',
  TRIGGER: 'Trigger',
  RELATIONSHIP: 'Relationship',
  COLUMN: 'Column',
  FUNCTION: [ 'func', 'ffunc', 'signal', 'slot', 'dcop', 'Public Member Functions', 'Static Public Member Functions', 'Protected Member Functions', 'Static Protected Member Functions', 'Private Member Functions', 'Static Private Member Functions', 'Package Functions', 'Static Package Functions', 'Functions/Subroutines', 'Function Prototypes', 'Public Slots', 'Signals', 'Protected Slots', 'Private Slots', 'Members', 'grammar' ],
  PROCEDURE: 'Procedure',
  SUBROUTINE: 'Subroutine',
  BUILTIN: 'Builtin',
  WORD: 'Word',
  CALLBACK: 'Callback',
  FIELD: 'Data Fields',
  PROPERTY: [ 'intfp', 'instp', 'Protected Properties', 'Public Properties', 'Inherited Properties', 'Private Properties' ],
  ATTRIBUTE: [ 'XML Attributes', 'Public Attributes', 'Static Public Attributes', 'Protected Attributes', 'Static Protected Attributes', 'Private Attributes', 'Static Private Attributes', 'Package Attributes', 'Static Package Attributes' ],
  ANNOTATION: 'Annotation',
  FILE: 'File',
  ENUM: [ 'Enumerations', 'enum' ],
  TACTIC: 'Tactic',
  ENVIRONMENT: 'Environment',
  COMMAND: 'Command',
  PROVISIONER: 'Provisioner',
  AXIOM: 'Axiom',
  LEMMA: 'Lemma',
  INDUCTIVE: 'Inductive',
  INSTANCE: 'Instance',
  GLOBAL: 'Global',
  TYPE: [ 'tag', 'tdef', 'Public Types', 'Protected Types', 'Private Types', 'Typedefs', 'Package Types', 'Data Types' ],
  UNION: 'Union',
  STRUCT: [ 'Data Structures', 'struct' ],
  VARIABLE: 'var',
  CONSTANT: [ 'clconst', 'econst', 'data', 'Notifications', 'enumelt', 'structdata'],
  MACRO: 'macro',
  VALUE: 'Value',
  VARIANT: 'Variant',
  DEFINE: 'Define',
  LITERAL: 'Literal',
  KEYWORD: 'Keyword',
  INSTRUCTION: 'Instruction',
  OPTION: 'Option',
  SETTING: 'Setting',
  STYLE: 'Style',
  NOTATION: 'Notation',
  ABBREVIATION: 'Abbreviation',
  PROJECTION: 'Projection',
  PARAMETER: 'Parameter',
  CONVERSION: 'Conversion',
  TEST: 'Test',
  OPERATOR: 'Operator',
  STATEMENT: 'Statement',
  SECTION: 'Section',
  UNKNOWN: 'Unknown'
};

module.exports = docset.types;
